blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from post import views as post_view
from registration import views as r_view, forms as reg_form
from .views import (HomeView, TrendingPosts, search_result_sync, follow_user, 
bookmark, draft, user_details, comment_reply, post_comment, comment_remove, reply_remove)

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('login/', r_view.RegLogin.as_view(),name='user_login'),
    path('signup/', r_view.signup, name='user_signup'),
    path('logout/', r_view.RegLogout.as_view(), name='user_logout'),
    path('user/', include('registration.urls')),
    path('notices/', include('notifiy.urls')),
    path('trending', TrendingPosts.as_view(), name='trending'),

    # apis
    path('api/search', search_result_sync, name='api_search'),
    path('api/follow', follow_user, name='api_follow'),
    path('api/bookmark', bookmark, name='api_bookmark'),
    path('api/draft', draft, name='api_draft'),
    path('api/userdetail', user_details, name='api_user'),
    path('api/reply',comment_reply, name='reply'),
    path('api/comment',post_comment, name='comment'),
    path('api/comment_remove',comment_remove, name='comment_remove'),
    path('api/reply_remove',reply_remove, name='reply_remove'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notifiy/urls.py
from django.urls import path
from .views import NoticeList

app_name='notifiy'

urlpatterns = [
    path('',NoticeList.as_view(), name='notifications')
]

registration/urls.py
from django.urls import path,include
from .views import UserDetail, ProfileView, PhotosList, UpdateProfileView, BookmarkView

app_name = 'registration'

urlpatterns = [
    path('',ProfileView.as_view(),name='myprofile'),
    path('<int:pk>/',UserDetail.as_view(),name='userprofile'),
    path('<int:pk>/update',UpdateProfileView.as_view(),name='updateprofile'),
    path('post/',include('post.urls')),
    path('photos/',PhotosList.as_view(), name='myphotos'),
    path('bookmark/', BookmarkView.as_view(), name='bookmark'),
]

blog/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.views.generic import TemplateView
from django.http import JsonResponse
from post.models import Post, reply, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from registration.models import Bookmarks
from itertools import zip_longest
from django.views.decorators.csrf import csrf_exempt

class HomeView(LoginRequiredMixin, TemplateView):
    template_name='home.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        following_list = list(self.request.user.userextend.get_following()) + [self.request.user,]
        p = Post.objects.filter(
            Q(user__in=following_list) &
            ~Q(visibility='3') &
            Q(draft=False)
        ).order_by('-created_on')
    
        ctx['post_list'] = p
        return ctx

class TrendingPosts(LoginRequiredMixin, TemplateView):
    template_name = 'blog/trending.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['topics'] = "FUTURE,CULTURE,TECH,ENTREPRENEURSHIP,PERSONAL,POLITICS,DESIGN,SCIENCE,POPULAR,MORE".split(',')

        ctx['topPost'] = Post.objects.all()[:3]
        return ctx

@login_required
def search_result_sync(request):
    data = request.GET.get('data', None)
    people_objects = []
    post_objects = []

    peoples = User.objects.filter(Q(username__icontains = data) | Q(first_name__icontains = data) | Q(last_name__icontains = data))
    posts = Post.objects.filter(Q(title__icontains = data) | Q(sub_title__icontains = data))

    for i, j in zip_longest(peoples, posts):
        if i is not None:
            people_objects.append({
            'id':i.pk,
            'name':i.get_full_name(), 
            'username':i.username, 
            'profile_pic':i.userextend.get_profile_pics().first().img.url if i.userextend.get_profile_pics().first() != None else i.userextend.get_avatar_url(stat=True),
            })

        if j is not None:
            post_objects.append({
            'id':j.pk,
            'title':j.title, 
            'subtitle':j.sub_title, 
            'img':j.head_img.url,
            })

    if not peoples:
        people_objects = False
    if not posts:
        post_objects = False

    ctx = {'peoples':people_objects, 'posts':post_objects}
    return JsonResponse(ctx)
  
@login_required
def follow_user(request):
    if request.method == 'POST':
        u = User.objects.get(pk=request.POST['user_id'])
        if u in request.user.userextend.following.all():
            request.user.userextend.following.remove(u)
            u.userextend.follower.remove(request.user)
            return JsonResponse({'status':False})
        else:
            request.user.userextend.following.add(u)
            u.userextend.follower.add(request.user)
            return JsonResponse({'status':True})
    else:
        return JsonResponse({'status': None})

@login_required
def bookmark(request):
    obj, created = Bookmarks.objects.get_or_create(user=request.user, o_id=request.GET.get('post_id'))

    if created:
        return JsonResponse({'status':True})
    else:
        obj.delete()    
        return JsonResponse({'status':False})

@login_required
def draft(request):
    p = Post.objects.get(pk=request.POST['post_id'])
    p.draft = not p.draft
    p.save()
    if p.draft:
        return JsonResponse({'status':True})
    else:
        return JsonResponse({'status':False})


def user_details(request):
    user = User.objects.get(username=request.GET['username'])
    ctx = {}
    ctx['name'] = user.get_full_name()
    ctx['profile_pic'] = user.userextend.get_profile_pics().first().img.url if len(user.userextend.get_profile_pics()) > 0 else user.userextend.get_avatar_url(stat=True)
    ctx['joined'] = user.date_joined.date()
    ctx['about'] = user.userextend.aboutMe
    ctx['top-posts'] = [(post.pk,post.title) for post in user.post_set.all().order_by('upvote')[:3]]
    ctx['followers'] = len(user.userextend.get_followers())
    return JsonResponse(ctx)

@login_required
@csrf_exempt
def comment_reply(request):
    if request.method == "POST":
        r = request.POST.get('reply','').strip(' ')
        if len(r) > 0:
            com = Comment.objects.get(pk=int(request.POST['comment_id']))
            print(com)
            r = reply(who=request.user, comment=com, content=r)
            r.save()
            return render_to_response('post/reply.html', context={'reply':r,'post':r.comment.post,})
    return JsonResponse({'status':False})


@login_required
@csrf_exempt
def post_comment(request):
    if request.method == "POST":
        c = request.POST.get('comment','').strip(" ")
        if len(c) > 0:
            p = Post.objects.get(pk=int(request.POST['post']))
            c = Comment(who=request.user, post=p, content=c)
            c.save()
        return render_to_response('post/comment.html', context={'comment':c, 'post':c.post,})

@login_required
@csrf_exempt
def comment_remove(request):
    if request.method == "POST":
        c = request.POST.get('id')
        c = get_object_or_404(Comment, pk=c)

        # if requested user is owner of comment or the owner of post

        if request.user == c.who or request.user == c.post.user:
            c.delete()
            return JsonResponse({'status':True})
        else:
            return JsonResponse({'status':False})


@login_required
@csrf_exempt
def reply_remove(request):
    if request.method == "POST":
        r = request.POST.get('id')
        r = get_object_or_404(reply, pk=r)

        # if requested user is owner of reply or the owner of post

        if request.user == r.who or request.user == r.comment.post.user:
            r.delete()
            return JsonResponse({'status':True})
        else:
            return JsonResponse({'status':False})

templates/blog/avatar_select_model.html
<div class="modal fade" id="AvatarSelect" tabindex="-1" role="dialog" aria-labelledby="AvatarSelectTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="AvatarSelectTitle">Choose your Avatar</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="d-flex flex-wrap justify-content-center" id="modal-container"></div>
        </div>
        <div class="modal-footer d-flex justify-content-center flex-row">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>

templates/blog/index.html
{% extends "base.html" %}
{% block title %}(4) {{user}} &middot; Blog{% endblock title %}
{% block content %}
    <div class="container mt-5">
        hi
    </div>
{% endblock content %}

templates/blog/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-info font-main py-0 pb-1 pb-lg-0 fixed-top">
    <i class="fas fa-bars" id="left-toggle"></i>
    <a class="navbar-brand font-secondary" href="{% url 'home' %}">
            &nbsp; <i>Rush</i>Time <small>Blogs</small></a>
    <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class=" w-md-50 mx-auto">
                <div class="input-group">
                    <input type="search" class="form-control form-control-sm border-0" placeholder="search here" aria-label="search" aria-describedby="search bar" id="search_bar">
                    <div class="input-group-append">
                        <button class="btn btn-light btn-sm border-0" type="button"><i class="fa fa-search"></i></button>
                    </div>
                </div>
                <div class="input-group">
                    <div id="search_sync" class="bg-white shadow p-1"></div>
                </div>
            </div>
            <ul class="navbar-nav ml-lg-auto flex-shrink-1 text-sm">
                <li class="nav-item">
                    <a class="nav-link text-center" href="{% url 'registration:post:new' %}" ><span class="d-md-none">New Post </span>  <i class="fa fa-plus" title="New Post"></i></a>
                </li>
                {% if request.user.is_authenticated %}
                {% comment %} notification panel {% endcomment %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-center" href="#" id="notificon" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="d-md-none">Notifications </span> <i class="fa fa-bell"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" style="max-height:400px; overflow-y: auto; overflow-x:hidden;" aria-labelledby="notificon">
                        <a class="dropdown-item py-1 px-1 bg-light my-1" href="{% url 'registration:myprofile' %}">
                        
                        </a>
                        <a class="dropdown-item py-1 px-1 bg-light my-1 text-primary" href="{% url 'notifiy:notifications' %}">
                        <small class="d-block text-center w-100 font-weight-bold">See all</small>
                        </a>
                    </div>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-center" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.is_authenticated %}
                       Hi, {{request.user.get_full_name}}
                    {% else %}
                        Login/Signup 
                    {% endif %}
                    <i class="fa fa-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'registration:myprofile' %}">Profile</a>
                    <a class="dropdown-item" href="#">New Post </a>
                    <div class="dropdown-divider"></div>
                    {% if request.user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'user_logout' %}">Logout <i class="fa fa-sign-out"></i></a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'user_login' %}">Login <i class="fa fa-sign-in"></i></a>
                    <a class="dropdown-item" href="{% url 'user_signup' %}">Signup <i class="fa fa-plus"></i></a>
                    {% endif %}
                    </div>
                </li>
            </ul>  
     </div>
</nav>

templates/blog/slider.html
<div class="w-100 slider d-flex justify-content-lg-center fixed-top bg-white font-main shadow" id="slider-1" style="{{style}}">
    {% for item in items %}
    <a href="#" class="{% if item == current %}active{% endif %} px-lg-5 pt-2 py-lg-1  px-2">{{item}}</a>
    {% endfor %}
</div>
<div style="margin-bottom:85px"></div>

templates/blog/trending.html
{% extends "base.html" %}
{% block title %}Trending Posts &middot; RushTime Blogs{% endblock title %}
{% block content %}
{% include "blog/slider.html" with items=topics style="margin-top:40px;" %}
<div class="container-fluid">
    
    <div class="row">
        <div class="col-lg-8 bg-success">
            Hello World
        </div>
        <div class="col-lg-4 bg-primary">Hello World</div>
    </div>
</div>
{% endblock content %}