blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from post import views as post_view
from registration import views as r_view, forms as reg_form
from .views import (HomeView, TrendingPosts, search_result_sync, follow_user, 
bookmark, draft, user_details, comment_reply, post_comment, comment_remove, reply_remove)

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('login/', r_view.RegLogin.as_view(),name='user_login'),
    path('signup/', r_view.signup, name='user_signup'),
    path('logout/', r_view.RegLogout.as_view(), name='user_logout'),
    path('user/', include('registration.urls')),
    path('notices/', include('notifiy.urls')),
    path('trending', TrendingPosts.as_view(), name='trending'),

    # apis
    path('api/search', search_result_sync, name='api_search'),
    path('api/follow', follow_user, name='api_follow'),
    path('api/bookmark', bookmark, name='api_bookmark'),
    path('api/draft', draft, name='api_draft'),
    path('api/userdetail', user_details, name='api_user'),
    path('api/reply',comment_reply, name='reply'),
    path('api/comment',post_comment, name='comment'),
    path('api/comment_remove',comment_remove, name='comment_remove'),
    path('api/reply_remove',reply_remove, name='reply_remove'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path,include
from .views import UserDetail, ProfileView, PhotosList, UpdateProfileView, BookmarkView

app_name = 'registration'

urlpatterns = [
    path('',ProfileView.as_view(),name='myprofile'),
    path('<int:pk>/',UserDetail.as_view(),name='userprofile'),
    path('<int:pk>/update',UpdateProfileView.as_view(),name='updateprofile'),
    path('post/',include('post.urls')),
    path('photos/',PhotosList.as_view(), name='myphotos'),
    path('bookmark/', BookmarkView.as_view(), name='bookmark'),
]

post/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.db.models import F
from django.conf import settings
from notifiy.models import Notice
from django.core.validators import validate_comma_separated_integer_list
from cloudinary import models as cmodels
import cloudinary
from django.utils.html import strip_tags

POST_TOPICS = (('0', 'PERSONAL'),('1', 'FUTURE'), ('2', 'CULTURE'), ('3', 'TECH'), ('4', 'ENTREPRENEURSHIP'), ('5', 'SELF'), ('6', 'POLITICS'), ('7', 'DESIGN'), ('8', 'SCIENCE'), ('9', 'POPULAR'))



# Create your models here.
class Post(models.Model):
    POST_VISIBILITY_CHOICE = (
        ('1','Public'),
        ('2','Only folowers'),
        ('3','Private')
    )
    DEFAULT_TOPIC = 1

    title = models.CharField(max_length=300)
    sub_title = models.CharField(max_length=150, blank=True)
    head_img = cmodels.CloudinaryField('images')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    draft = models.BooleanField(default=False)
    upvote = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    visibility = models.CharField(max_length=1, choices=POST_VISIBILITY_CHOICE, default='1')
    post_tags = models.CharField(max_length=255, help_text='Tags seperated with a space')
    post_topic= models.CharField(max_length=1, choices=POST_TOPICS, default='0')
    def __str__(self):
        return self.title

    def add_upvote(self, username):
        self.upvote = models.F('upvote') + 1
        PostLikers.objects.create(post=self, user = username)
        self.save()

    def remove_upvote(self, username):
        self.upvote = F('upvote') - 1
        PostLikers.objects.filter(post=self, user=username).delete()
        self.save()

    def all_likers(self):
        l = [i.users_id for i in self.likers.all()]
        return l

    def get_read_time(self):
        time = len(strip_tags(self.content).split(' ')) / 255
        return round(time)

    def get_comments_count(self) :
        return len(self.comment_set.all())

    def get_short_story(self):
        return strip_tags(self.content)[:200]+'...'

    def save(self):
        super().save()
        followers = self.user.userextend.get_followers()
        text = self.user.get_full_name() + " just posted."
        print(followers)
        for u in followers:
            if self.created_on == self.updated_on:
                Notice.objects.create(user=u.current_user,sender=self.user,text=text, category='1', c_id=self.pk)


class Comment(models.Model):
    who = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    likes = models.PositiveIntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.who.username

    def save(self):
        super().save()
        text= " commented on your Post."
        if (self.post.user != self.who) and (self.created_on == self.updated_on):
            Notice.objects.create(user=self.post.user,sender=self.who,text=text, category='2', c_id=self.pk)

class reply(models.Model):
    who = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.who.username

    def save(self):
        super().save()
        text= self.who.get_full_name() + " Just replied on your Post."
        if self.comment.post.user != self.who and self.created_on == self.updated_on:
            Notice.objects.create(user=self.comment.post.user,sender=self.who,text=text, category='3', c_id=self.pk)

class PostLikers(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='likers')
    users_id = models.IntegerField()

    def __str__(self):
        return str(self.users_id)

notifiy/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Notice

# Create your views here.

class NoticeList(ListView):
    model = Notice
    template_name = 'notifiy/notice.html'

    def get_queryset(self, *args, **kwargs):
        query = Notice.objects.filter(user=self.request.user).order_by('-date_time')
        return query

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <style>#load{width:100%;height:100%;position:fixed;z-index:9999;background:url("{% static 'registration/imgs/loaders/audio.svg' %}") no-repeat center center #34919f; }</style>
    <meta charset="UTF-8">
    <meta name="theme-color" content="#17a2b8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no,maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Vidaloka" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="shortcut icon" href="/static/registration/fevicon.png" type="image/x-icon">
    {% block op_style %}{% endblock op_style %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body {% block class %}{% endblock class %}>
    {% include "blog/navbar.html" %}
    {% block navbar %}{% endblock navbar %}
    <div id="load"></div>
    <div id="contents"> 
        {% if request.user.is_authenticated %}
            {% include "sidebar.html" %}
        {% endif %}
        {% block content %}{% endblock content %}
        {% block footer %}{% endblock footer %}
    </div>
    <script>document.onreadystatechange=function(){var e=document.readyState;"interactive"==e?document.getElementById("contents").style.visibility="hidden":"complete"==e&&setTimeout(function(){document.getElementById("interactive"),document.getElementById("load").style.visibility="hidden",document.getElementById("contents").style.visibility="visible"},500)};</script>
    <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5b4b49914a104f0011ca68b3&product=inline-share-buttons' async='async'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/master.js' %}"></script>
    {% block op_script %}{% endblock op_script %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}{{request.user}}(5) &middot; Blog Home{% endblock title %}

{% block content %}
<div class="container mt-5 px-0">
    <div class="d-flex flex-column">
        
        {% for i in post_list %}
        <div class="">{% include "post/post_card_v2.html" with post=i %}</div>
            
        {% empty %}
        <div class="mx-2 ">
            <p class="mx-auto">Humm... it seems you donot follow anyone yet. No problem Let follow some click below or Read some of the best articles around the world.</p>
            <div class="mx-auto d-block">
                <a href="#" class="btn btn-primary">Search Peoples</a>
                <a href="#" class="btn btn-primary">Top articles</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/sidebar.html
{% load static %}
<div id="left-bar" class="bg-info shadow text-white" style="display:none">
    <div class="list-group mt-2  border-0 font-main">
        <a href="/" class="list-group-item list-group-item-action rounded-0"><i class="fas fa-home"></i> Home</a>
        <a href="{% url 'trending' %}" class="list-group-item list-group-item-action"><i class="fas fa-fire"></i> Trending</a>
        <a href="{% url 'registration:bookmark' %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center"><span><i class="far fa-bookmark"></i> Bookmarks</span> 
            <span class="badge badge-info badge-pill">{{request.user.bookmarks.all|length}}</span>
        </a>
        <a href="#" class="list-group-item list-group-item-action"><i class="fas fa-newspaper"></i> Posts</a>
        <a href="#" class="list-group-item list-group-item-action rounded-0"><i class="fas fa-images"></i> Photos</a>
    </div>
    <div class="list-group mt-2 font-weight-bold px-2">
        Your Network 
    </div>
    <div class="list-group mt-2 border-0 font-main">
        {% for u in request.user.userextend.get_following %}
        <a href="{% url 'registration:userprofile' pk=u.pk %}" class="list-group-item list-group-item-action d-flex p-1 rounded-0">
            <div class="border bookmark-user-img rounded-circle d-inline-block" style="background-image: url('{% if u.userextend.get_profile_pics|length > 0 %}{{u.userextend.get_profile_pics.first.img.url}}{% else %}{% static u.userextend.get_avatar_url %}{% endif %}');"></div>
            <div class="d-inline-block pl-2 w-100">
                <div class="d-block">{{u.get_full_name}}</div>
                <div>
                    <span class="d-inline-block border-right pr-2 text-warning">Followers: {{u.userextend.get_followers|length}}</span>
                    <span class="d-inline-block border-right pr-2 text-info">Following: {{u.userextend.get_followings|length}}</span>
                    <span class="d-inline-block text-primary">Posts: {{u.post_set.all|length}}</span>
                </div>
            </div>
        </a>
        
        {% endfor %}
    </div>
    <div class="text-center mt-1">
        <small class="d-block">RushTime Blogs &copy; {% now 'Y' %}</small>
    </div>
</div>