blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from post import views as post_view
from registration import views as r_view, forms as reg_form
from .views import (HomeView, TrendingPosts, search_result_sync, follow_user, 
bookmark, draft, user_details, comment_reply, post_comment, comment_remove, reply_remove)

urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('login/', r_view.RegLogin.as_view(),name='user_login'),
    path('signup/', r_view.signup, name='user_signup'),
    path('logout/', r_view.RegLogout.as_view(), name='user_logout'),
    path('user/', include('registration.urls')),
    path('notices/', include('notifiy.urls')),
    path('trending', TrendingPosts.as_view(), name='trending'),

    # apis
    path('api/search', search_result_sync, name='api_search'),
    path('api/follow', follow_user, name='api_follow'),
    path('api/bookmark', bookmark, name='api_bookmark'),
    path('api/draft', draft, name='api_draft'),
    path('api/userdetail', user_details, name='api_user'),
    path('api/reply',comment_reply, name='reply'),
    path('api/comment',post_comment, name='comment'),
    path('api/comment_remove',comment_remove, name='comment_remove'),
    path('api/reply_remove',reply_remove, name='reply_remove'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from post.views import PostDetailView, PostCreateView, PostUpdateView, PostLike, PostDeleteView

app_name="post"

urlpatterns = [
    path('<int:pk>',PostDetailView.as_view(), name='detail'),
    path('new', PostCreateView.as_view(), name='new'),
    path('<int:pk>/update', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='delete'),
    path('api/like/',PostLike, name='postlike')
]

registration/urls.py
from django.urls import path,include
from .views import UserDetail, ProfileView, PhotosList, UpdateProfileView, BookmarkView

app_name = 'registration'

urlpatterns = [
    path('',ProfileView.as_view(),name='myprofile'),
    path('<int:pk>/',UserDetail.as_view(),name='userprofile'),
    path('<int:pk>/update',UpdateProfileView.as_view(),name='updateprofile'),
    path('post/',include('post.urls')),
    path('photos/',PhotosList.as_view(), name='myphotos'),
    path('bookmark/', BookmarkView.as_view(), name='bookmark'),
]

post/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.db.models import F
from django.conf import settings
from notifiy.models import Notice
from django.core.validators import validate_comma_separated_integer_list
from cloudinary import models as cmodels
import cloudinary
from django.utils.html import strip_tags

POST_TOPICS = (('0', 'PERSONAL'),('1', 'FUTURE'), ('2', 'CULTURE'), ('3', 'TECH'), ('4', 'ENTREPRENEURSHIP'), ('5', 'SELF'), ('6', 'POLITICS'), ('7', 'DESIGN'), ('8', 'SCIENCE'), ('9', 'POPULAR'))



# Create your models here.
class Post(models.Model):
    POST_VISIBILITY_CHOICE = (
        ('1','Public'),
        ('2','Only folowers'),
        ('3','Private')
    )
    DEFAULT_TOPIC = 1

    title = models.CharField(max_length=300)
    sub_title = models.CharField(max_length=150, blank=True)
    head_img = cmodels.CloudinaryField('images')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    draft = models.BooleanField(default=False)
    upvote = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    visibility = models.CharField(max_length=1, choices=POST_VISIBILITY_CHOICE, default='1')
    post_tags = models.CharField(max_length=255, help_text='Tags seperated with a space')
    post_topic= models.CharField(max_length=1, choices=POST_TOPICS, default='0')
    def __str__(self):
        return self.title

    def add_upvote(self, username):
        self.upvote = models.F('upvote') + 1
        PostLikers.objects.create(post=self, user = username)
        self.save()

    def remove_upvote(self, username):
        self.upvote = F('upvote') - 1
        PostLikers.objects.filter(post=self, user=username).delete()
        self.save()

    def all_likers(self):
        l = [i.users_id for i in self.likers.all()]
        return l

    def get_read_time(self):
        time = len(strip_tags(self.content).split(' ')) / 255
        return round(time)

    def get_comments_count(self) :
        return len(self.comment_set.all())

    def get_short_story(self):
        return strip_tags(self.content)[:200]+'...'

    def save(self):
        super().save()
        followers = self.user.userextend.get_followers()
        text = self.user.get_full_name() + " just posted."
        print(followers)
        for u in followers:
            if self.created_on == self.updated_on:
                Notice.objects.create(user=u.current_user,sender=self.user,text=text, category='1', c_id=self.pk)


class Comment(models.Model):
    who = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    likes = models.PositiveIntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.who.username

    def save(self):
        super().save()
        text= " commented on your Post."
        if (self.post.user != self.who) and (self.created_on == self.updated_on):
            Notice.objects.create(user=self.post.user,sender=self.who,text=text, category='2', c_id=self.pk)

class reply(models.Model):
    who = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.who.username

    def save(self):
        super().save()
        text= self.who.get_full_name() + " Just replied on your Post."
        if self.comment.post.user != self.who and self.created_on == self.updated_on:
            Notice.objects.create(user=self.comment.post.user,sender=self.who,text=text, category='3', c_id=self.pk)

class PostLikers(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE, related_name='likers')
    users_id = models.IntegerField()

    def __str__(self):
        return str(self.users_id)

post/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields = ['title','sub_title','head_img','content','draft','visibility','post_tags','post_topic']

post/views.py
from django.shortcuts import redirect, resolve_url
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from . import models
from registration.models import Images, UserExtend
from django.db.models import Q,F
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView
from .forms import PostCreateForm
from notifiy.models import Notice
from django.http import JsonResponse
# Create your views here.
Post_Topics_List = {'0': 'PERSONAL', '1': 'FUTURE', '2': 'CULTURE', '3': 'TECH', '4': 'ENTREPRENEURSHIP', '5': 'SELF', '6': 'POLITICS', '7': 'DESIGN', '8': 'SCIENCE', '9': 'POPULAR'}
class PostDetailView(LoginRequiredMixin, DetailView):
    model = models.Post
    template_name = 'post/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        g = self.request.GET.get('read', False)
        sl = self.object.user.userextend.protected
        ctx = super().get_context_data(**kwargs)
        ctx['topics'] = [Post_Topics_List[t] for t in self.object.user.post_set.values_list('post_topic', flat=True).distinct()]
        if g:
            n = Notice.objects.get(pk=g)
            n.viewed = True
            n.save()
        if self.object.user == self.request.user:
            ctx['lock'] = False # all allowed
            ctx['me'] = True
        else:
            ctx['me'] = False
            if sl == '3':
                ctx['lock'] = False # all allowed
            elif sl == '2':
                if self.object.user in self.request.user.userextend.get_following():
                    ctx['lock'] = False # all allowed
                else:
                    ctx['lock'] = True # no allowed
            else:
                ctx['lock'] = True # no allowed
                ctx['superlock'] = True
        return ctx

class PostCreateView(LoginRequiredMixin, CreateView):
    model = models.Post
    form_class = PostCreateForm
    template_name = 'post/post_create.html'
    success_url = '/'
    initial = {}

    def get_context_data(self, **kwargs):
        self.user = self.request.user
        self.initial = {
            'visibility':self.request.user.userextend.Post_Type}
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

@login_required
def PostLike(request):
    p = models.Post.objects.get(id=request.GET.get('post_id'))
    liker, created = p.likers.get_or_create(users_id=request.user.pk) 
    
    if not created:
        liker.delete()
        p.upvote = F('upvote') - 1
    else :
        p.upvote = F('upvote') + 1
    
    p.save()
    p.refresh_from_db()
    return JsonResponse(data={'status':created,'likes':int(p.upvote)})


class PostUpdateView(UpdateView):
    model = models.Post
    # fields = ['title','sub_title','head_img','content','draft','visibility']
    form_class = PostCreateForm
    template_name = 'post/post_update.html'
    success_url = '/'
    initial = {}

    def get_context_data(self, **kwargs):
        self.initial = {'visibility':self.request.user.userextend.Post_Type}
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PostDeleteView(DeleteView):
    template_name = 'post/delete_post.html'
    model = models.Post
    success_url= '/user/'

templates/post/comment.html
{% load static %}
<div class="card my-2 shadow" id="c_{{comment.pk}}">
    <div class="row p-2">
        <div class="col-2">
            <a href="{% url 'registration:userprofile' pk=comment.who.pk %}">
            <div class="post-extend-user-img rounded-circle border-info border-top border-bottom" 
            {% if comment.who.userextend.get_profile_pics|length > 0 %}
            style="background-image: url('{comment.who.userextend.get_profile_pics.first.img.url}}');"
            {% else %}
            style="background-color:white;background-image: url('{% static comment.who.userextend.get_avatar_url %}');"
            {% endif %}>
            </div></a>
        </div>
        <div class="col-10 d-flex flex-column">
            <p class="lead m-0">{{comment.who.get_full_name}} {% if post.user == comment.who %}<small><span class="badge badge-primary">Author</span></small>{% endif %}</p>
            <p class="text-muted"><small>{{comment.created_on|timesince}} ago</small></p>
        </div>
    </div>
    <div class="card-body">
        <p class="card-text mb-0">{{comment.content}}</p>
        <div class="text-right text-xs">
            <a href="#" class="r_btn" data-id='{{comment.pk}}'>Reply ({{comment.reply_set.all|length}}) <i class="fas fa-share ml-auto"></i></a>
            {% if comment.who == request.user or request.user == post.user %}
            <a href="#" onclick="remove_comment({{comment.pk}})" class="remove_cmt text-danger ml-2">Remove <i class="fas fa-trash ml-auto"></i></a>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-12">
                {% for reply in comment.reply_set.all reversed %}
                    {% include "post/reply.html" with reply=reply %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/post/delete_post.html
{% extends "base.html" %}
{% block title %}
Delete Post - {{post.title}}
{% endblock title %}

{% block content %}
    <div class="container mt-5 d-flex mb-2 mx-0">
        <div class="row">
            <div class="mx-auto col-lg-3 pb-2">
                <h2 class="text-center">Delete Post confirm?</h2>
                <form method="post" class="text-center">
                    {% csrf_token %}
                    <a href="{% url 'registration:myprofile' %}#id_post_{{post.pk}}" class="btn btn-primary"><i class="fas fa-arrow-left"></i> Go Back</a>
                    <button type="submit" class="btn btn-danger">Delete confirm</button>
                </form>
            </div>
            <div class="col-lg-9">
                {% include "post/post_card_v2.html" %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/post/post_card.html
{% load static %}
<div class="card rounded-0 post-card-mw my-2" id="id_post_{{post.id}}">
    <div class="card-header py-1 px-0">
        <div class="row m-0">
            <div class="col-10"> 
                <div class="d-flex ">
                    <a href="
                    {% if post.user == request.user %}
                    {% url 'registration:myprofile' %}
                    {% else %}
                    {% url 'registration:userprofile' pk=post.user.pk %}
                    {% endif %}
                    ">
                     <div class="border post-user-img rounded-circle" 
                        {% if post.user.userextend.get_profile_pics|length > 0 %}
                            style="background-image: url('{{post.user.userextend.get_profile_pics.first.img.url}}');"
                        {% else %}
                            style="background-image: url('/static/registration/imgs/user.png');"
                        {% endif %}

                        >
                    </div>
                    
                    </a>
                    <div class="flex-column justify-content-start ml-2">
                        <p class="post-username"><a href="
                            {% if post.user == request.user %}
                            {% url 'registration:myprofile' %}
                            {% else %}
                            {% url 'registration:userprofile' pk=post.user.pk %}
                            {% endif %}" data-user='{{ post.user.username }}' onmouseover="pop(this)"
                     class="link-no-style">{{post.user.get_full_name}}</a> <span class="text-muted d-none d-md-inline text-capitalize">programmer by heart</span></p>
                        <p class="post-since-time text-muted p-0">about {{ post.created_on|timesince }} ago <span>&middot; {{ post.get_read_time }} min read</span></p>
                        
                    </div>   
                </div>
            </div>
            <div class="col-2">
                <div class="d-flex justify-content-end">
                    {% if post.user == request.user %}
                    <button onclick="draft({{post.id}}, '{{csrf_token}}')" class="btn btn-outline-info btn-sm mr-2 {% if post.draft %}active{% endif %}"
                    title="Draft" id="draft_{{post.pk}}">{% if post.draft %} <i class="fas fa-lock"></i> {% else %} <i class="fas fa-unlock"></i> {% endif %}</button>
                    {% endif %}

                    <button onclick="bookmark({{post.id}})" class="btn btn-outline-success btn-sm
                    {% if post.pk in request.user.userextend.get_bookmarks %}
                    active
                    {% endif %}
                    " title="Bookmark" id="bookmark_{{post.pk}}"><i class="far fa-bookmark"></i></button>
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'registration:post:detail' pk=post.pk %}" class="post-card_link">
    <div class="card-body p-0">
        <div class="card-title h3 px-2 title text-dark">{{post.title}}</div>
        <div class="card-subtitle text-muted px-2">{{post.sub_title}}</div>
        <div class="card-text">
            <img src="
            {% if post.head_img %}
            {{post.head_img.url}}
            {% else %}
            {% static 'registration/imgs/bg.jpg'  %}
            {% endif %}
            " alt="Its just a joke" class="img-fluid post-front-img mx-auto d-block">
        </div>
    </a>     
    </div>
    <!-- footer -->
    <div id="share_panel-{{post.pk}}" class="px-1" style="display:none">
        <div class="sharethis-inline-share-buttons my-2" data-url="{{ request.get_host }}{% url 'registration:post:detail' pk=post.pk %}"></div>
    </div>
    <div class="card-footer py-1 px-0 d-flex align-items-center" style="height:30px">
        
        <div><button class="btn btn-sm mx-2 btn-outline-danger nofocus py-0
            {% if request.user.id in post.all_likers %} active {% endif %}
            " id="like_{{post.pk}}" title="Like it" onclick="likeit({{post.pk}})"><i class="far fa-heart" title="Love it"></i></button></div>
        
        <div><a href="{% url 'registration:post:detail' pk=post.pk %}#comment" class="btn btn-sm mx-2 btn-outline-info py-0" title="Comments"><i class="far fa-comment-alt"></i></a></div>
        
        <button class="btn btn-sm mx-2 btn-outline-primary nofocus py-0" onclick="showShare('#share_panel-{{post.pk}}')" type="button" id="share_btn" title="Share"><i class="fas fa-share"></i></button>

        <div class="dropup ml-auto">
            <button class="btn btn-sm mx-2 btn-outline-dark dropdown-toggle notificon border-0 rounded-circle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="more">
                <i class="fas fa-cog"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                {% if request.user == post.user %}
                    
                {% else %}
                <a class="dropdown-item disable" href="#"><i class="fas fa-exclamation text-danger mr-1"></i> Report</a>
                {% endif %}
                
                <a class="dropdown-item disable" href="#">beta</a>
                {% if post.user == request.user and request.resolver_match.url_name == 'myprofile' %}
                <a class="dropdown-item " href="{% url 'registration:post:delete' pk=post.pk %}"><i class="far fa-trash-alt"></i> Delete</a>
                {% endif %}
            </div>
        </div>
    </div>  
</div>

templates/post/post_card_extend.html
<div class="card border-0">
    <div class="card-header p-1">
        <div class="row m-0">
            <div class="col-10"> 
                <div class="d-flex ">
                    <a href="
                    {% if post.user == request.user %}
                    {% url 'registration:myprofile' %}
                    {% else %}
                    {% url 'registration:userprofile' pk=post.user.pk %}
                    {% endif %}
                    "><img src="
                        {% if profile_pic.img %}
                        {{profile_pic.img.url}}
                        {% else %}
                        {% static user.userextend.get_avatar_url %}
                        {% endif %}"
                     alt="user" class="border post-user-img rounded-circle"></a>
                    <div class="flex-column justify-content-start ml-2">
                        <p class="post-username"><a href="
                            {% if post.user == request.user %}
                            {% url 'registration:myprofile' %}
                            {% else %}
                            {% url 'registration:userprofile' pk=post.user.pk %}
                            {% endif %}"
                     class="link-no-style">{{post.user.get_full_name}}</a> <span class="text-muted d-none d-md-inline text-capitalize">programmer by heart</span></p>
                        <p class="post-since-time text-muted">{{post.created_on|timesince}}</p>
                    </div>   
                </div>
            </div>
            <div class="col-2">
                <div class="d-flex justify-content-end">
                    <a href="#" class="btn btn-outline-warning btn-sm" title="Bookmark"><i class="fa fa-bookmark-o"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body p-1">
        <div class="card-title h4 px-2">{{post.title}}</div>
        <div class="card-subtitle text-muted px-2">Its just a joke</div>
        <div class="card-text p-5">
            <img src="{% static 'registration/imgs/demo.png' %}" alt="Its just a joke" class="img-fluid post-front-img mx-auto d-block">
            <div class="post-text mx-2">{{post.content|safe}}</div>
        </div>        
    </div>
    <!-- comment -->
    <div class="card-footer mh-100 pb-5 px-lg-5">  
        <div class="card-text d-flex flex-column" id="comment-box">
            {% for c in post.comment_set.all %}
                <span class="post-comment-text">
                    <span class="post-username"><a href="#" class="link-no-style">{{c.who}}</a> :</span>
                    <small class="text-muted">{{c.content}}
                    <a href="#"><i class="fa fa-thumbs-up"></i> (34)</a>
                    <a href="#"><i class="fa fa-comments-o"></i> (2)</a></small>
                </span>
            {% empty %}
            <small class="d-block text-center text-muted">No Comments yet</small>
            {% endfor %}
        </div>
        <small class="p-0 text-center d-block" id="comment-box-opener"><i class="fa fa-ellipsis-h"></i></small>
    </div>
    <div class="card-footer py-1 px-0 fixed-bottom bg-light">
        <div class="d-flex justify-content-center">
            <button class="btn btn-sm mx-2 btn-outline-primary" title="level up"><i class="fa fa-level-up"></i> (400+)</button>
            <button class="btn btn-sm mx-2 btn-outline-secondary" title="level down"><i class="fa fa-level-down"></i> (200+)</button>
            <button class="btn btn-sm mx-2 btn-outline-info" title="share"><i class="fa fa-share"></i> (20+)</button>
        </div>
    </div>  
</div>

templates/post/post_card_v2.html
{% load static %}
<div class="card mb-2 post-card-mw shadow mx-lg-auto rounded-0">
        <a href="{% url 'registration:post:detail' pk=post.pk %}" class="text-muted">    
        <div class="card-img-top bookmark-img"  
        {% if post.head_img %}
            style="background-image: url('{{post.head_img.url}}');"
        {% else %}
            style="background-image: url('/static/registration/imgs/user.png');"
        {% endif %} ></div>
        </a>
        <div class="card-img-overlay bg-dark py-2" style="height:60px;opacity:0.95">
            <small class="card-title d-flex flex-row align-items-center">
                <a id="post_id_{{post.pk}}" href="{% if post.user == request.user %}{% url 'registration:myprofile' %}{% else %}{% url 'registration:userprofile' pk=post.user.pk %}{% endif %}" data-user='{{ post.user.username }}' onmouseover="pop(this)">
                <div class="border bookmark-user-img rounded-circle" 
                {% if post.user.userextend.get_profile_pics|length > 0 %}
                    style="background-image: url('{{post.user.userextend.get_profile_pics.first.img.url}}');"
                {% else %}
                    style="background-color:white;background-image: url('{% static post.user.userextend.get_avatar_url %}');"
                {% endif %}
                ></div>
                </a>
                <div class="">
                    <span class="text-white shadow-sm px-3 rounded bg-dark ml-2 border" style="opacity:0.6;">{{post.user.get_full_name}} &middot; 2 min read</span>
                    <span class="text-white shadow-sm px-3 rounded bg-dark ml-2 border d-block mt-1" style="opacity:0.6;">posted {{post.updated_on|timesince}} ago</span>
                </div>
                
                <div class="ml-auto">
                        {% if request.user == post.user %}
                        <span class='text-muted' id="draft_{{post.pk}}">
                            {% if post.draft %}
                            <i class="fas fa-lock text-muted"></i> Draft
                            {% else %}
                            <i class="fas fa-unlock text-info"></i> Live
                            {% endif %}
                        </span>
                        {% endif %}
                        <a onclick="bookmark({{post.id}})" class="text-light cursor" title="Bookmark" id="bookmark_{{post.pk}}"> 
                            {% if post.pk in request.user.userextend.get_bookmarks %}
                            <i class="fas fa-bookmark"></i>
                            {% else %}
                            <i class="far fa-bookmark"></i>
                            {% endif %}
                        </a> 
                    

                <!-- dropdown -->
                    <div class="dropdown d-inline-block">
                        <a class="text-white dropdown-toggle notificon btn-sm" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v"></i>
                        </a>
                        
                        <div class="dropdown-menu p-0 dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                            {% if post.user == request.user %}
                            <a href="{% url 'registration:post:delete' pk=post.pk %}" class="dropdown-item"><i class="fas fa-trash text-danger"></i> Delete post</a>  
                            <a class="dropdown-item" href="#" onclick="draft({{post.pk}},'{{csrf_token}}')"><i class="fas fa-exchange-alt"></i>  Draft switch</a>
                            {% endif %}
                            
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>     
            </small>
        </div>
        
        <div class="card-body pb-0 z-back">
            <a href="{% url 'registration:post:detail' pk=post.pk %}" class="text-muted">
                <h5 class="card-title font-secondary">{{post.title}}</h5>
                <p class="card-text font-italic border-left pl-1 py-1 mb-1">{{post.sub_title}}</p>
                <p class="card-text m-0 font-main">{{post.get_short_story}}</p>
            </a>
            <p class="card-text">
                <div class="text-center">
                    <div class="row">
                        <div class="col-6">
                            <button class="btn btn-sm mx-2 btn-outline-info nofocus py-0 btn-block
                            {% if request.user.id in post.all_likers %} active {% endif %}
                            " id="like_{{post.pk}}" title="Like it" onclick="likeit({{post.pk}})"><i class="far fa-heart" title="Love it"></i>&nbsp;{% if post.upvote > 0 %}{{ post.upvote }}{% endif %}</button>
                        </div>
                        <div class="col-6">
                            <a href="{% url 'registration:post:detail' pk=post.pk %}#comment" class="btn btn-sm mx-2 btn-outline-info nofocus py-0 btn-block" title="Comments"><i class="far fa-comment-alt"></i>&nbsp;{% if post.get_comments_count > 0 %}{{ post.get_comments_count }}{% endif %}</a>
                        </div>
                    </div>
                    <div class="sharethis-inline-share-buttons mt-1" style="max-height:33px" data-url="{% url 'registration:post:detail' pk=post.pk %}"></div>
                </div></p>
        </div>
</div>

templates/post/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{post.title}} &middot; {{post.user}} : Blog
{% endblock title %}
{% block op_style %} <link rel="stylesheet" href="{% static 'post/css/post-detail.css' %}"> {% endblock op_style %}
{% block content %}
{% include "blog/slider.html" with items=topics style="margin-top:40px;" current=post.get_post_topic_display %}
<div class="container-fluid px-0"> 
    {% include "post/post_extend.html" %}
</div>
{% endblock content %}

{% block op_script %}
<script src="{% static 'post/js/post_detail.js' %}"></script>
{% endblock op_script %}

templates/post/reply.html
{% load static %}
<div class="card my-2 shadow" id="r_{{reply.pk}}">
    <div class="row p-2">
        <div class="col-2">
            <a href="{% url 'registration:userprofile' pk=post.user.pk %}">
            <div class="post-extend-user-img rounded-circle border-info border-top border-bottom" 
            {% if reply.who.userextend.get_profile_pics|length > 0 %}
            style="background-image: url('{{reply.who.userextend.get_profile_pics.first.img.url}}');"
            {% else %}
            style="background-color:white;background-image: url('{% static reply.who.userextend.get_avatar_url %}');"
            {% endif %}>
            </div></a>
        </div>
        <div class="col-10 d-flex flex-column">
            <p class="lead m-0 pl-1">{{reply.who.get_full_name}} {% if post.user == reply.who %}<small><span class="badge badge-primary">Author</span></small>{% endif %}</p>
            <p class="text-muted pl-1"><small>{{reply.created_on|timesince}} ago</small></p>
        </div>
    </div>
    <div class="card-body pt-0">
        <p class="card-text mb-0">{{reply.content}}</p>
        {% if reply.who == request.user or request.user == post.user %}
            <div class="text-right text-xs"> 
                <a href="#" onclick="remove_reply({{reply.pk}})" class="text-danger">Remove <i class="fas fa-trash ml-auto"></i></a>
            </div>
        {% endif %}
    </div>
</div>